apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: nextjs-app
  app.kubernetes.io/instance: nextjs-app-instance
  app.kubernetes.io/name: nextjs-app
commonAnnotations:
  app.openshift.io/vcs-uri: "https://github.com/cloud-native-garage-method-cohort/matt-eugen-next-app"